import type {SidebarsConfig} from "@docusaurus/plugin-content-docs";

import ApiSidebar from './docs/api/sidebar';

const sidebars: SidebarsConfig = {
	docs: [
		'introduction',
		'dashboard',
		'account',
		{
			type: "category",
			label: "Projects",
			items: [
				{
					type: "autogenerated",
					dirName: "payment",
				},
			],
		},
		{
			type: "category",
			label: "Monitoring",
			items: [
				{
					type: "autogenerated",
					dirName: "monitoring",
				},
			],
		},
		{
			type: "category",
			label: "Testomato BOT",
			items: [
				{
					type: "autogenerated",
					dirName: "bot",
				},
			],
		},
		{
			type: "category",
			label: "Checks",
			items: [
				{
					type: "autogenerated",
					dirName: "checks",
				},
			],
		},
		{
			type: "category",
			label: "API Reference",
			items: ApiSidebar,
		},
		{
			type: "doc",
			id: "support",
		},
	],
};

export default sidebars;